# Assignment 2 IRS - With Synonyms

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [114]:
# required imports
import numpy as np
import fnmatch
import os


Suppose we have 3 files containing data :

### File Contents

!["This is my book" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f1.png?raw=true)
!["This is my pen" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f2.png?raw=true)
!["This is book is intersting" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f3.png?raw=true)

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [115]:
# Here we have initialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set


In [116]:
#Your code starts here   
files = ["myfile1.txt", "myfile2.txt", "myfile3.txt", "f1.txt","f2.txt", "f3.txt"]
file_count = len(files)
i = 0
for file_name in files:
    f = "files/" + file_name
    files_dict[f] = i
    i += 1

for key in files_dict:
    print(files_dict[key])
#Your code ends here       

0
1
2
3
4
5


Displaying the count of files.

In [117]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 6


Displaying Dictionary containing all files.

In [118]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'files/myfile1.txt': 0, 'files/myfile2.txt': 1, 'files/myfile3.txt': 2, 'files/f1.txt': 3, 'files/f2.txt': 4, 'files/f3.txt': 5}


# Step 3 Extract Unique Vocabulary

write code to print all the unique words in every file and store them in a set

In [119]:
#Your code starts here    
print("Unique words in every file:")
for file_name in files_dict:
    f = open(file_name, 'r')
    data = f.read()
    data = data.split(" ")
    for element in data:
        unique_word_set.add(element)
    f.close()

print(unique_word_set)
print("Count of files",'\t',  file_count)
#Your code ends here

Unique words in every file:
{'books', 'Pakistan', 'country', 'match', 'my', 'interesting', 'the', 'book', 'is', 'pen', 'a', 'has', 'baeutiful', 'Library', 'This', 'Won', 'My'}
Count of files 	 6


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o1.png?raw=true)


# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

1. Create Term doc matrix such that colmns will be unique words and all the files will be rows
2. Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [120]:
data_size = len(unique_word_set)
TERM_DOC_MATRIX = np.zeros((file_count, data_size), dtype=int)
print(TERM_DOC_MATRIX)
# creating a dictionary of unique words and thier indices against them
words_dict = {}
i = 0
for e in unique_word_set:
    words_dict[e] = i
    i += 1

print(f"Dictionary of unique words:\n {words_dict}" )
print(f"Dictionary of files:\n {files_dict}")
    


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Dictionary of unique words:
 {'books': 0, 'Pakistan': 1, 'country': 2, 'match': 3, 'my': 4, 'interesting': 5, 'the': 6, 'book': 7, 'is': 8, 'pen': 9, 'a': 10, 'has': 11, 'baeutiful': 12, 'Library': 13, 'This': 14, 'Won': 15, 'My': 16}
Dictionary of files:
 {'files/myfile1.txt': 0, 'files/myfile2.txt': 1, 'files/myfile3.txt': 2, 'files/f1.txt': 3, 'files/f2.txt': 4, 'files/f3.txt': 5}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o2.png?raw=true)

# Step 5 Fill Term Document Matrix

1. Fill the term doc matrix by checking if the unique word exists in a file or not
2. If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
3. Do the same for all the files present in the directory

In [121]:
#Your code starts here    
print(f"Dictionary of unique words:\n {words_dict}\n" )
print("Term Document Matrix")
# words_mat = np.zeros((file_count, data_size), dtype=object)
# iterating all files data to find the unique words and updating term document matrix based on the word
for unique_word in unique_word_set:
    for file in files_dict:
        f = open(file, 'r')
        data = f.read()
        data = data.split()
        if unique_word in data:
            TERM_DOC_MATRIX[files_dict[file]][words_dict[unique_word]] = 1
#             words_mat[files_dict[file]][words_dict[unique_word]] = unique_word
        f.close()
print(TERM_DOC_MATRIX)
#Your code ends here

Dictionary of unique words:
 {'books': 0, 'Pakistan': 1, 'country': 2, 'match': 3, 'my': 4, 'interesting': 5, 'the': 6, 'book': 7, 'is': 8, 'pen': 9, 'a': 10, 'has': 11, 'baeutiful': 12, 'Library': 13, 'This': 14, 'Won': 15, 'My': 16}

Term Document Matrix
[[0 1 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0]
 [0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o4.png?raw=true)


# Step 6 Ask for a user Query

For user query make a column vector of length of all the unique words present in a set

In [122]:
#Your code starts here    
colVector = np.zeros((len(unique_word_set), 1), dtype=int)
colVector

#Your code ends here

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o5.png?raw=true)


In [123]:
query = input("\nWrite something for searching:  ")
print("Query is:", query) #this is a fascinating publication written with a ballpoint


Write something for searching:  this is a fascinating publication written with a ballpoint
Query is: this is a fascinating publication written with a ballpoint


### Expected Output

![Expected Output of query](images/Query.png)

# Step 7 Load Synonyms

In [130]:
synonym_file_path = r"files\synonyms.txt"
synonyms_dict = {} # dictionary to store synonyms
#your code starts here
file = open(synonym_file_path)
data = file.readlines()
for line in data:
    ss = line.strip().split(':')
    key = ss[0]
    value = ss[1].split(',')
    words = [v.strip() for v in value]
    synonyms_dict[key] = words
    


#your code ends here

print("\nSynonyms Dictionary\n")
print(synonyms_dict)


Synonyms Dictionary

{'write': ['compose', 'draft', 'author', 'create'], 'file': ['document', 'record', 'dossier', 'report'], 'example': ['illustration', 'instance', 'sample', 'demonstration'], 'query': ['question', 'inquiry', 'search', 'request'], 'synonym': ['equivalent', 'substitute', 'alternate', 'replacement'], 'retrieve': ['fetch', 'recover', 'obtain', 'bring back'], 'system': ['framework', 'structure', 'organization', 'arrangement'], 'search': ['seek', 'look for', 'explore', 'examine'], 'lost': ['misplaced', 'missing', 'forgotten', 'mislaid'], 'pen': ['write', 'ink', 'ballpoint', 'fountain'], 'paper': ['document', 'sheet', 'form', 'letter'], 'book': ['novel', 'volume', 'publication', 'tome'], 'read': ['peruse', 'scan', 'study', 'look at'], 'interesting': ['fascinating', 'engaging', 'intriguing', 'absorbing'], 'computer': ['machine', 'device', 'processor', 'laptop'], 'software': ['program', 'application', 'app', 'platform']}


### Expected Output

![Synonym Dict Example](images\Synonym_dict.png)

# Step 8 Extend User Query

In [131]:
expanded_query = []
# Write code to expand the query using synonyms
#your code starts here
# print(query)
splitted_query = query.split()
for word in splitted_query:
    expanded_query.append(word)
    for key in synonyms_dict:
        for val in synonyms_dict[key]:
            
            if val == word:
                expanded_query.append(key)
#                 print(expanded_query)


#your code ends here

print("Expanded Query")
print(expanded_query)

Expanded Query
['this', 'is', 'a', 'fascinating', 'interesting', 'publication', 'book', 'written', 'with', 'a', 'ballpoint', 'pen']


### Expected Output

![Extended Query](images\Expanded_Query.png)

Now work with extended query and find the relevant documents.

In [126]:
# Check every word of query if it exists in the set of unique words or not
# If exists then increment the count of that word in word dictionary


In [132]:
#Your code starts here    

# replacing all the synonyms with its keys in the expanded query
for i in range(len(expanded_query)):
    for key in synonyms_dict:
        if expanded_query[i] in synonyms_dict[key]:
            expanded_query[i] = key
            
# print(expanded_query)

# updating col_vector
for word in expanded_query:
    if word in unique_word_set:
        colVector[words_dict[word]][0] += 1


print(colVector)
#Your code ends here
#Your code ends here

[[0]
 [0]
 [0]
 [0]
 [0]
 [4]
 [0]
 [4]
 [2]
 [4]
 [4]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o6.png?raw=true)


# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [133]:
#Your code starts here  
resultant = np.dot(TERM_DOC_MATRIX, colVector)
print(f'result\n{resultant}')
print(f'max_index\n{np.argmax(resultant)}')
print(f'max\n{np.max(resultant)}')
#Your code ends here

result
[[ 6]
 [ 0]
 [ 0]
 [ 6]
 [ 6]
 [10]]
max_index
5
max
10


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o7.png?raw=true)


# Step 8 Display the contents of file


Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [134]:
#Your code starts here    
maxim = np.argmax(resultant)
for file in files_dict:
    if files_dict[file] == maxim:
        f = open(file, 'r')
        data = f.read()
        print(f'{file}\n{data}')
        f.close()

#Your code ends here

files/f3.txt
My book is interesting


Congratulations Now you are able to build your own small IRS which can work even if query does not have exact same words.